// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: coins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCoins = `-- name: CountCoins :one
SELECT count(*) FROM coins
`

func (q *Queries) CountCoins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCoins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoin = `-- name: CreateCoin :one
INSERT INTO coins (
    country, year, face_value, currency, material, description, km_code,
    min_value, max_value, grade, sample_image_url_front, sample_image_url_back,
    notes, gemini_details
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, country, year, face_value, currency, material, description, km_code, min_value, max_value, grade, sample_image_url_front, sample_image_url_back, notes, gemini_details, created_at, updated_at
`

type CreateCoinParams struct {
	Country             string         `json:"country"`
	Year                int32          `json:"year"`
	FaceValue           string         `json:"face_value"`
	Currency            string         `json:"currency"`
	Material            string         `json:"material"`
	Description         pgtype.Text    `json:"description"`
	KmCode              pgtype.Text    `json:"km_code"`
	MinValue            pgtype.Numeric `json:"min_value"`
	MaxValue            pgtype.Numeric `json:"max_value"`
	Grade               pgtype.Text    `json:"grade"`
	SampleImageUrlFront pgtype.Text    `json:"sample_image_url_front"`
	SampleImageUrlBack  pgtype.Text    `json:"sample_image_url_back"`
	Notes               pgtype.Text    `json:"notes"`
	GeminiDetails       []byte         `json:"gemini_details"`
}

func (q *Queries) CreateCoin(ctx context.Context, arg CreateCoinParams) (Coin, error) {
	row := q.db.QueryRow(ctx, createCoin,
		arg.Country,
		arg.Year,
		arg.FaceValue,
		arg.Currency,
		arg.Material,
		arg.Description,
		arg.KmCode,
		arg.MinValue,
		arg.MaxValue,
		arg.Grade,
		arg.SampleImageUrlFront,
		arg.SampleImageUrlBack,
		arg.Notes,
		arg.GeminiDetails,
	)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.Year,
		&i.FaceValue,
		&i.Currency,
		&i.Material,
		&i.Description,
		&i.KmCode,
		&i.MinValue,
		&i.MaxValue,
		&i.Grade,
		&i.SampleImageUrlFront,
		&i.SampleImageUrlBack,
		&i.Notes,
		&i.GeminiDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoin = `-- name: DeleteCoin :exec
DELETE FROM coins
WHERE id = $1
`

func (q *Queries) DeleteCoin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoin, id)
	return err
}

const getCoin = `-- name: GetCoin :one
SELECT id, country, year, face_value, currency, material, description, km_code, min_value, max_value, grade, sample_image_url_front, sample_image_url_back, notes, gemini_details, created_at, updated_at FROM coins
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCoin(ctx context.Context, id pgtype.UUID) (Coin, error) {
	row := q.db.QueryRow(ctx, getCoin, id)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.Year,
		&i.FaceValue,
		&i.Currency,
		&i.Material,
		&i.Description,
		&i.KmCode,
		&i.MinValue,
		&i.MaxValue,
		&i.Grade,
		&i.SampleImageUrlFront,
		&i.SampleImageUrlBack,
		&i.Notes,
		&i.GeminiDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoins = `-- name: ListCoins :many
SELECT id, country, year, face_value, currency, material, description, km_code, min_value, max_value, grade, sample_image_url_front, sample_image_url_back, notes, gemini_details, created_at, updated_at FROM coins
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCoinsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCoins(ctx context.Context, arg ListCoinsParams) ([]Coin, error) {
	rows, err := q.db.Query(ctx, listCoins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coin
	for rows.Next() {
		var i Coin
		if err := rows.Scan(
			&i.ID,
			&i.Country,
			&i.Year,
			&i.FaceValue,
			&i.Currency,
			&i.Material,
			&i.Description,
			&i.KmCode,
			&i.MinValue,
			&i.MaxValue,
			&i.Grade,
			&i.SampleImageUrlFront,
			&i.SampleImageUrlBack,
			&i.Notes,
			&i.GeminiDetails,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoin = `-- name: UpdateCoin :one
UPDATE coins
SET
    country = $2,
    year = $3,
    face_value = $4,
    currency = $5,
    material = $6,
    description = $7,
    km_code = $8,
    min_value = $9,
    max_value = $10,
    grade = $11,
    sample_image_url_front = $12,
    sample_image_url_back = $13,
    notes = $14,
    gemini_details = $15,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, country, year, face_value, currency, material, description, km_code, min_value, max_value, grade, sample_image_url_front, sample_image_url_back, notes, gemini_details, created_at, updated_at
`

type UpdateCoinParams struct {
	ID                  pgtype.UUID    `json:"id"`
	Country             string         `json:"country"`
	Year                int32          `json:"year"`
	FaceValue           string         `json:"face_value"`
	Currency            string         `json:"currency"`
	Material            string         `json:"material"`
	Description         pgtype.Text    `json:"description"`
	KmCode              pgtype.Text    `json:"km_code"`
	MinValue            pgtype.Numeric `json:"min_value"`
	MaxValue            pgtype.Numeric `json:"max_value"`
	Grade               pgtype.Text    `json:"grade"`
	SampleImageUrlFront pgtype.Text    `json:"sample_image_url_front"`
	SampleImageUrlBack  pgtype.Text    `json:"sample_image_url_back"`
	Notes               pgtype.Text    `json:"notes"`
	GeminiDetails       []byte         `json:"gemini_details"`
}

func (q *Queries) UpdateCoin(ctx context.Context, arg UpdateCoinParams) (Coin, error) {
	row := q.db.QueryRow(ctx, updateCoin,
		arg.ID,
		arg.Country,
		arg.Year,
		arg.FaceValue,
		arg.Currency,
		arg.Material,
		arg.Description,
		arg.KmCode,
		arg.MinValue,
		arg.MaxValue,
		arg.Grade,
		arg.SampleImageUrlFront,
		arg.SampleImageUrlBack,
		arg.Notes,
		arg.GeminiDetails,
	)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.Year,
		&i.FaceValue,
		&i.Currency,
		&i.Material,
		&i.Description,
		&i.KmCode,
		&i.MinValue,
		&i.MaxValue,
		&i.Grade,
		&i.SampleImageUrlFront,
		&i.SampleImageUrlBack,
		&i.Notes,
		&i.GeminiDetails,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
