// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: coins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCoins = `-- name: CountCoins :one
SELECT count(*) FROM coins
`

func (q *Queries) CountCoins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCoins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoin = `-- name: CreateCoin :one
INSERT INTO coins (
    id, name, mint, mintage, country, year, face_value, currency, material, description, km_code,
    min_value, max_value, grade, technical_notes, gemini_details, group_id, personal_notes,
    weight_g, diameter_mm, thickness_mm, edge, shape,
    acquired_at, sold_at, price_paid, sold_price
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $23,
    $24, $25, $26, $27
) RETURNING id, name, mint, mintage, country, year, face_value, currency, material, description, km_code, min_value, max_value, grade, technical_notes, gemini_details, group_id, personal_notes, weight_g, diameter_mm, thickness_mm, edge, shape, acquired_at, sold_at, price_paid, sold_price, created_at, updated_at
`

type CreateCoinParams struct {
	ID             pgtype.UUID    `json:"id"`
	Name           pgtype.Text    `json:"name"`
	Mint           pgtype.Text    `json:"mint"`
	Mintage        pgtype.Int8    `json:"mintage"`
	Country        pgtype.Text    `json:"country"`
	Year           pgtype.Int4    `json:"year"`
	FaceValue      pgtype.Text    `json:"face_value"`
	Currency       pgtype.Text    `json:"currency"`
	Material       pgtype.Text    `json:"material"`
	Description    pgtype.Text    `json:"description"`
	KmCode         pgtype.Text    `json:"km_code"`
	MinValue       pgtype.Numeric `json:"min_value"`
	MaxValue       pgtype.Numeric `json:"max_value"`
	Grade          NullGradeType  `json:"grade"`
	TechnicalNotes pgtype.Text    `json:"technical_notes"`
	GeminiDetails  []byte         `json:"gemini_details"`
	GroupID        pgtype.Int4    `json:"group_id"`
	PersonalNotes  pgtype.Text    `json:"personal_notes"`
	WeightG        pgtype.Numeric `json:"weight_g"`
	DiameterMm     pgtype.Numeric `json:"diameter_mm"`
	ThicknessMm    pgtype.Numeric `json:"thickness_mm"`
	Edge           pgtype.Text    `json:"edge"`
	Shape          pgtype.Text    `json:"shape"`
	AcquiredAt     pgtype.Date    `json:"acquired_at"`
	SoldAt         pgtype.Date    `json:"sold_at"`
	PricePaid      pgtype.Numeric `json:"price_paid"`
	SoldPrice      pgtype.Numeric `json:"sold_price"`
}

func (q *Queries) CreateCoin(ctx context.Context, arg CreateCoinParams) (Coin, error) {
	row := q.db.QueryRow(ctx, createCoin,
		arg.ID,
		arg.Name,
		arg.Mint,
		arg.Mintage,
		arg.Country,
		arg.Year,
		arg.FaceValue,
		arg.Currency,
		arg.Material,
		arg.Description,
		arg.KmCode,
		arg.MinValue,
		arg.MaxValue,
		arg.Grade,
		arg.TechnicalNotes,
		arg.GeminiDetails,
		arg.GroupID,
		arg.PersonalNotes,
		arg.WeightG,
		arg.DiameterMm,
		arg.ThicknessMm,
		arg.Edge,
		arg.Shape,
		arg.AcquiredAt,
		arg.SoldAt,
		arg.PricePaid,
		arg.SoldPrice,
	)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mint,
		&i.Mintage,
		&i.Country,
		&i.Year,
		&i.FaceValue,
		&i.Currency,
		&i.Material,
		&i.Description,
		&i.KmCode,
		&i.MinValue,
		&i.MaxValue,
		&i.Grade,
		&i.TechnicalNotes,
		&i.GeminiDetails,
		&i.GroupID,
		&i.PersonalNotes,
		&i.WeightG,
		&i.DiameterMm,
		&i.ThicknessMm,
		&i.Edge,
		&i.Shape,
		&i.AcquiredAt,
		&i.SoldAt,
		&i.PricePaid,
		&i.SoldPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoin = `-- name: DeleteCoin :exec
DELETE FROM coins
WHERE id = $1
`

func (q *Queries) DeleteCoin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoin, id)
	return err
}

const getCoin = `-- name: GetCoin :one
SELECT id, name, mint, mintage, country, year, face_value, currency, material, description, km_code, min_value, max_value, grade, technical_notes, gemini_details, group_id, personal_notes, weight_g, diameter_mm, thickness_mm, edge, shape, acquired_at, sold_at, price_paid, sold_price, created_at, updated_at FROM coins
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCoin(ctx context.Context, id pgtype.UUID) (Coin, error) {
	row := q.db.QueryRow(ctx, getCoin, id)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mint,
		&i.Mintage,
		&i.Country,
		&i.Year,
		&i.FaceValue,
		&i.Currency,
		&i.Material,
		&i.Description,
		&i.KmCode,
		&i.MinValue,
		&i.MaxValue,
		&i.Grade,
		&i.TechnicalNotes,
		&i.GeminiDetails,
		&i.GroupID,
		&i.PersonalNotes,
		&i.WeightG,
		&i.DiameterMm,
		&i.ThicknessMm,
		&i.Edge,
		&i.Shape,
		&i.AcquiredAt,
		&i.SoldAt,
		&i.PricePaid,
		&i.SoldPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoins = `-- name: ListCoins :many
SELECT id, name, mint, mintage, country, year, face_value, currency, material, description, km_code, min_value, max_value, grade, technical_notes, gemini_details, group_id, personal_notes, weight_g, diameter_mm, thickness_mm, edge, shape, acquired_at, sold_at, price_paid, sold_price, created_at, updated_at FROM coins
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCoinsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCoins(ctx context.Context, arg ListCoinsParams) ([]Coin, error) {
	rows, err := q.db.Query(ctx, listCoins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coin
	for rows.Next() {
		var i Coin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mint,
			&i.Mintage,
			&i.Country,
			&i.Year,
			&i.FaceValue,
			&i.Currency,
			&i.Material,
			&i.Description,
			&i.KmCode,
			&i.MinValue,
			&i.MaxValue,
			&i.Grade,
			&i.TechnicalNotes,
			&i.GeminiDetails,
			&i.GroupID,
			&i.PersonalNotes,
			&i.WeightG,
			&i.DiameterMm,
			&i.ThicknessMm,
			&i.Edge,
			&i.Shape,
			&i.AcquiredAt,
			&i.SoldAt,
			&i.PricePaid,
			&i.SoldPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoin = `-- name: UpdateCoin :one
UPDATE coins
SET
    name = $2,
    mint = $3,
    mintage = $4,
    country = $5,
    year = $6,
    face_value = $7,
    currency = $8,
    material = $9,
    description = $10,
    km_code = $11,
    min_value = $12,
    max_value = $13,
    grade = $14,
    technical_notes = $15,
    gemini_details = $16,
    group_id = $17,
    personal_notes = $18,
    weight_g = $19,
    diameter_mm = $20,
    thickness_mm = $21,
    edge = $22,
    shape = $23,
    acquired_at = $24,
    sold_at = $25,
    price_paid = $26,
    sold_price = $27,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, mint, mintage, country, year, face_value, currency, material, description, km_code, min_value, max_value, grade, technical_notes, gemini_details, group_id, personal_notes, weight_g, diameter_mm, thickness_mm, edge, shape, acquired_at, sold_at, price_paid, sold_price, created_at, updated_at
`

type UpdateCoinParams struct {
	ID             pgtype.UUID    `json:"id"`
	Name           pgtype.Text    `json:"name"`
	Mint           pgtype.Text    `json:"mint"`
	Mintage        pgtype.Int8    `json:"mintage"`
	Country        pgtype.Text    `json:"country"`
	Year           pgtype.Int4    `json:"year"`
	FaceValue      pgtype.Text    `json:"face_value"`
	Currency       pgtype.Text    `json:"currency"`
	Material       pgtype.Text    `json:"material"`
	Description    pgtype.Text    `json:"description"`
	KmCode         pgtype.Text    `json:"km_code"`
	MinValue       pgtype.Numeric `json:"min_value"`
	MaxValue       pgtype.Numeric `json:"max_value"`
	Grade          NullGradeType  `json:"grade"`
	TechnicalNotes pgtype.Text    `json:"technical_notes"`
	GeminiDetails  []byte         `json:"gemini_details"`
	GroupID        pgtype.Int4    `json:"group_id"`
	PersonalNotes  pgtype.Text    `json:"personal_notes"`
	WeightG        pgtype.Numeric `json:"weight_g"`
	DiameterMm     pgtype.Numeric `json:"diameter_mm"`
	ThicknessMm    pgtype.Numeric `json:"thickness_mm"`
	Edge           pgtype.Text    `json:"edge"`
	Shape          pgtype.Text    `json:"shape"`
	AcquiredAt     pgtype.Date    `json:"acquired_at"`
	SoldAt         pgtype.Date    `json:"sold_at"`
	PricePaid      pgtype.Numeric `json:"price_paid"`
	SoldPrice      pgtype.Numeric `json:"sold_price"`
}

func (q *Queries) UpdateCoin(ctx context.Context, arg UpdateCoinParams) (Coin, error) {
	row := q.db.QueryRow(ctx, updateCoin,
		arg.ID,
		arg.Name,
		arg.Mint,
		arg.Mintage,
		arg.Country,
		arg.Year,
		arg.FaceValue,
		arg.Currency,
		arg.Material,
		arg.Description,
		arg.KmCode,
		arg.MinValue,
		arg.MaxValue,
		arg.Grade,
		arg.TechnicalNotes,
		arg.GeminiDetails,
		arg.GroupID,
		arg.PersonalNotes,
		arg.WeightG,
		arg.DiameterMm,
		arg.ThicknessMm,
		arg.Edge,
		arg.Shape,
		arg.AcquiredAt,
		arg.SoldAt,
		arg.PricePaid,
		arg.SoldPrice,
	)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mint,
		&i.Mintage,
		&i.Country,
		&i.Year,
		&i.FaceValue,
		&i.Currency,
		&i.Material,
		&i.Description,
		&i.KmCode,
		&i.MinValue,
		&i.MaxValue,
		&i.Grade,
		&i.TechnicalNotes,
		&i.GeminiDetails,
		&i.GroupID,
		&i.PersonalNotes,
		&i.WeightG,
		&i.DiameterMm,
		&i.ThicknessMm,
		&i.Edge,
		&i.Shape,
		&i.AcquiredAt,
		&i.SoldAt,
		&i.PricePaid,
		&i.SoldPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
