// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCoinLink = `-- name: AddCoinLink :one
INSERT INTO coin_links (
    coin_id, url, name, og_title, og_description, og_image
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, coin_id, url, name, og_title, og_description, og_image, created_at
`

type AddCoinLinkParams struct {
	CoinID        pgtype.UUID `json:"coin_id"`
	Url           string      `json:"url"`
	Name          pgtype.Text `json:"name"`
	OgTitle       pgtype.Text `json:"og_title"`
	OgDescription pgtype.Text `json:"og_description"`
	OgImage       pgtype.Text `json:"og_image"`
}

func (q *Queries) AddCoinLink(ctx context.Context, arg AddCoinLinkParams) (CoinLink, error) {
	row := q.db.QueryRow(ctx, addCoinLink,
		arg.CoinID,
		arg.Url,
		arg.Name,
		arg.OgTitle,
		arg.OgDescription,
		arg.OgImage,
	)
	var i CoinLink
	err := row.Scan(
		&i.ID,
		&i.CoinID,
		&i.Url,
		&i.Name,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCoinLink = `-- name: DeleteCoinLink :exec
DELETE FROM coin_links
WHERE id = $1
`

func (q *Queries) DeleteCoinLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoinLink, id)
	return err
}

const listCoinLinks = `-- name: ListCoinLinks :many
SELECT id, coin_id, url, name, og_title, og_description, og_image, created_at FROM coin_links
WHERE coin_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCoinLinks(ctx context.Context, coinID pgtype.UUID) ([]CoinLink, error) {
	rows, err := q.db.Query(ctx, listCoinLinks, coinID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoinLink
	for rows.Next() {
		var i CoinLink
		if err := rows.Scan(
			&i.ID,
			&i.CoinID,
			&i.Url,
			&i.Name,
			&i.OgTitle,
			&i.OgDescription,
			&i.OgImage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
