// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Coin struct {
	ID                  pgtype.UUID        `json:"id"`
	Country             string             `json:"country"`
	Year                int32              `json:"year"`
	FaceValue           string             `json:"face_value"`
	Currency            string             `json:"currency"`
	Material            string             `json:"material"`
	Description         pgtype.Text        `json:"description"`
	KmCode              pgtype.Text        `json:"km_code"`
	MinValue            pgtype.Numeric     `json:"min_value"`
	MaxValue            pgtype.Numeric     `json:"max_value"`
	Grade               pgtype.Text        `json:"grade"`
	SampleImageUrlFront pgtype.Text        `json:"sample_image_url_front"`
	SampleImageUrlBack  pgtype.Text        `json:"sample_image_url_back"`
	Notes               pgtype.Text        `json:"notes"`
	GeminiDetails       []byte             `json:"gemini_details"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
