// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CoinSide string

const (
	CoinSideFront CoinSide = "front"
	CoinSideBack  CoinSide = "back"
)

func (e *CoinSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoinSide(s)
	case string:
		*e = CoinSide(s)
	default:
		return fmt.Errorf("unsupported scan type for CoinSide: %T", src)
	}
	return nil
}

type NullCoinSide struct {
	CoinSide CoinSide `json:"coin_side"`
	Valid    bool     `json:"valid"` // Valid is true if CoinSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoinSide) Scan(value interface{}) error {
	if value == nil {
		ns.CoinSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoinSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoinSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoinSide), nil
}

type ImageType string

const (
	ImageTypeOriginal  ImageType = "original"
	ImageTypeCrop      ImageType = "crop"
	ImageTypeThumbnail ImageType = "thumbnail"
	ImageTypeSample    ImageType = "sample"
)

func (e *ImageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImageType(s)
	case string:
		*e = ImageType(s)
	default:
		return fmt.Errorf("unsupported scan type for ImageType: %T", src)
	}
	return nil
}

type NullImageType struct {
	ImageType ImageType `json:"image_type"`
	Valid     bool      `json:"valid"` // Valid is true if ImageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImageType) Scan(value interface{}) error {
	if value == nil {
		ns.ImageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImageType), nil
}

type Coin struct {
	ID                pgtype.UUID        `json:"id"`
	Name              pgtype.Text        `json:"name"`
	Mint              pgtype.Text        `json:"mint"`
	Mintage           pgtype.Int8        `json:"mintage"`
	Country           pgtype.Text        `json:"country"`
	Year              pgtype.Int4        `json:"year"`
	FaceValue         pgtype.Text        `json:"face_value"`
	Currency          pgtype.Text        `json:"currency"`
	Material          pgtype.Text        `json:"material"`
	Description       pgtype.Text        `json:"description"`
	KmCode            pgtype.Text        `json:"km_code"`
	MinValue          pgtype.Numeric     `json:"min_value"`
	MaxValue          pgtype.Numeric     `json:"max_value"`
	Grade             pgtype.Text        `json:"grade"`
	TechnicalNotes    pgtype.Text        `json:"technical_notes"`
	GeminiDetails     []byte             `json:"gemini_details"`
	NumistaDetails    []byte             `json:"numista_details"`
	GroupID           pgtype.Int4        `json:"group_id"`
	PersonalNotes     pgtype.Text        `json:"personal_notes"`
	WeightG           pgtype.Numeric     `json:"weight_g"`
	DiameterMm        pgtype.Numeric     `json:"diameter_mm"`
	ThicknessMm       pgtype.Numeric     `json:"thickness_mm"`
	Edge              pgtype.Text        `json:"edge"`
	Shape             pgtype.Text        `json:"shape"`
	NumistaNumber     pgtype.Int4        `json:"numista_number"`
	AcquiredAt        pgtype.Date        `json:"acquired_at"`
	SoldAt            pgtype.Date        `json:"sold_at"`
	PricePaid         pgtype.Numeric     `json:"price_paid"`
	SoldPrice         pgtype.Numeric     `json:"sold_price"`
	GeminiModel       pgtype.Text        `json:"gemini_model"`
	GeminiTemperature pgtype.Numeric     `json:"gemini_temperature"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CoinImage struct {
	ID               pgtype.UUID        `json:"id"`
	CoinID           pgtype.UUID        `json:"coin_id"`
	ImageType        ImageType          `json:"image_type"`
	Side             CoinSide           `json:"side"`
	Path             string             `json:"path"`
	Extension        string             `json:"extension"`
	Size             int64              `json:"size"`
	Width            int32              `json:"width"`
	Height           int32              `json:"height"`
	MimeType         string             `json:"mime_type"`
	OriginalFilename pgtype.Text        `json:"original_filename"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
