// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCoinLink(ctx context.Context, arg AddCoinLinkParams) (CoinLink, error)
	CountCoins(ctx context.Context) (int64, error)
	CreateCoin(ctx context.Context, arg CreateCoinParams) (Coin, error)
	CreateCoinGalleryImage(ctx context.Context, arg CreateCoinGalleryImageParams) (CoinGalleryImage, error)
	CreateCoinImage(ctx context.Context, arg CreateCoinImageParams) (CoinImage, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupImage(ctx context.Context, arg CreateGroupImageParams) (GroupImage, error)
	DeleteCoin(ctx context.Context, id pgtype.UUID) error
	DeleteCoinGalleryImage(ctx context.Context, id pgtype.UUID) error
	DeleteCoinLink(ctx context.Context, id pgtype.UUID) error
	DeleteGroup(ctx context.Context, id int32) error
	DeleteGroupImage(ctx context.Context, id pgtype.UUID) error
	GetAllCoins(ctx context.Context) ([]Coin, error)
	GetAllValues(ctx context.Context) ([]pgtype.Numeric, error)
	GetAverageValue(ctx context.Context) (float64, error)
	GetCoin(ctx context.Context, id pgtype.UUID) (Coin, error)
	GetCountryDistribution(ctx context.Context) ([]GetCountryDistributionRow, error)
	GetDistinctSaleChannels(ctx context.Context) ([]pgtype.Text, error)
	GetGradeDistribution(ctx context.Context) ([]GetGradeDistributionRow, error)
	GetGroupByName(ctx context.Context, name string) (Group, error)
	GetGroupDistribution(ctx context.Context) ([]GetGroupDistributionRow, error)
	GetGroupStats(ctx context.Context) ([]GetGroupStatsRow, error)
	GetHeaviestCoin(ctx context.Context) (Coin, error)
	GetMaterialDistribution(ctx context.Context) ([]GetMaterialDistributionRow, error)
	GetOldestCoin(ctx context.Context) (Coin, error)
	GetRandomCoin(ctx context.Context) (Coin, error)
	GetRarestCoins(ctx context.Context, limit int32) ([]Coin, error)
	GetSmallestCoin(ctx context.Context) (Coin, error)
	GetTotalValue(ctx context.Context) (float64, error)
	GetTotalWeightByMaterial(ctx context.Context, material pgtype.Text) (float64, error)
	ListCoinGalleryImages(ctx context.Context, coinID pgtype.UUID) ([]CoinGalleryImage, error)
	ListCoinImagesByCoinID(ctx context.Context, coinID pgtype.UUID) ([]CoinImage, error)
	ListCoinImagesByCoinIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]CoinImage, error)
	ListCoinLinks(ctx context.Context, coinID pgtype.UUID) ([]CoinLink, error)
	ListCoins(ctx context.Context, arg ListCoinsParams) ([]Coin, error)
	ListGroupImages(ctx context.Context, groupID int32) ([]GroupImage, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListRecentCoins(ctx context.Context) ([]Coin, error)
	ListTopValuableCoins(ctx context.Context) ([]Coin, error)
	MarkCoinAsSold(ctx context.Context, arg MarkCoinAsSoldParams) (Coin, error)
	UpdateCoin(ctx context.Context, arg UpdateCoinParams) (Coin, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
}

var _ Querier = (*Queries)(nil)
