// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCoins(ctx context.Context) (int64, error)
	CreateCoin(ctx context.Context, arg CreateCoinParams) (Coin, error)
	CreateCoinImage(ctx context.Context, arg CreateCoinImageParams) (CoinImage, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	DeleteCoin(ctx context.Context, id pgtype.UUID) error
	GetCoin(ctx context.Context, id pgtype.UUID) (Coin, error)
	GetGroupByName(ctx context.Context, name string) (Group, error)
	ListCoinImagesByCoinID(ctx context.Context, coinID pgtype.UUID) ([]CoinImage, error)
	ListCoins(ctx context.Context, arg ListCoinsParams) ([]Coin, error)
	ListGroups(ctx context.Context) ([]Group, error)
	UpdateCoin(ctx context.Context, arg UpdateCoinParams) (Coin, error)
}

var _ Querier = (*Queries)(nil)
