// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: sell.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDistinctSaleChannels = `-- name: GetDistinctSaleChannels :many
SELECT DISTINCT sale_channel
FROM coins
WHERE sale_channel IS NOT NULL AND sale_channel != ''
ORDER BY sale_channel
`

func (q *Queries) GetDistinctSaleChannels(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getDistinctSaleChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var sale_channel pgtype.Text
		if err := rows.Scan(&sale_channel); err != nil {
			return nil, err
		}
		items = append(items, sale_channel)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCoinAsSold = `-- name: MarkCoinAsSold :one
UPDATE coins
SET
    sold_at = $2,
    sold_price = $3,
    sale_channel = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, mint, mintage, country, year, face_value, currency, material, description, km_code, min_value, max_value, grade, technical_notes, gemini_details, numista_details, group_id, personal_notes, weight_g, diameter_mm, thickness_mm, edge, shape, numista_number, acquired_at, sold_at, price_paid, sold_price, sale_channel, gemini_model, gemini_temperature, numista_search, ruler, orientation, series, commemorated_topic, created_at, updated_at
`

type MarkCoinAsSoldParams struct {
	ID          pgtype.UUID    `json:"id"`
	SoldAt      pgtype.Date    `json:"sold_at"`
	SoldPrice   pgtype.Numeric `json:"sold_price"`
	SaleChannel pgtype.Text    `json:"sale_channel"`
}

func (q *Queries) MarkCoinAsSold(ctx context.Context, arg MarkCoinAsSoldParams) (Coin, error) {
	row := q.db.QueryRow(ctx, markCoinAsSold,
		arg.ID,
		arg.SoldAt,
		arg.SoldPrice,
		arg.SaleChannel,
	)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mint,
		&i.Mintage,
		&i.Country,
		&i.Year,
		&i.FaceValue,
		&i.Currency,
		&i.Material,
		&i.Description,
		&i.KmCode,
		&i.MinValue,
		&i.MaxValue,
		&i.Grade,
		&i.TechnicalNotes,
		&i.GeminiDetails,
		&i.NumistaDetails,
		&i.GroupID,
		&i.PersonalNotes,
		&i.WeightG,
		&i.DiameterMm,
		&i.ThicknessMm,
		&i.Edge,
		&i.Shape,
		&i.NumistaNumber,
		&i.AcquiredAt,
		&i.SoldAt,
		&i.PricePaid,
		&i.SoldPrice,
		&i.SaleChannel,
		&i.GeminiModel,
		&i.GeminiTemperature,
		&i.NumistaSearch,
		&i.Ruler,
		&i.Orientation,
		&i.Series,
		&i.CommemoratedTopic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
