ALTER TABLE coins ADD COLUMN ruler TEXT NOT NULL DEFAULT '';
ALTER TABLE coins ADD COLUMN orientation TEXT NOT NULL DEFAULT '';
ALTER TABLE coins ADD COLUMN series TEXT NOT NULL DEFAULT '';
ALTER TABLE coins ADD COLUMN commemorated_topic TEXT NOT NULL DEFAULT '';
