FROM golang:1.25-bookworm

RUN apt-get update && apt-get install -y libvips-dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/img-test ./cmd/img-test/main.go

CMD ["/app/img-test"]
