// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/antonioparicio/numismaticapp/internal/domain (interfaces: AIService)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mocks/mock_ai_service.go -package=mocks github.com/antonioparicio/numismaticapp/internal/domain AIService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/antonioparicio/numismaticapp/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAIService is a mock of AIService interface.
type MockAIService struct {
	ctrl     *gomock.Controller
	recorder *MockAIServiceMockRecorder
	isgomock struct{}
}

// MockAIServiceMockRecorder is the mock recorder for MockAIService.
type MockAIServiceMockRecorder struct {
	mock *MockAIService
}

// NewMockAIService creates a new mock instance.
func NewMockAIService(ctrl *gomock.Controller) *MockAIService {
	mock := &MockAIService{ctrl: ctrl}
	mock.recorder = &MockAIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIService) EXPECT() *MockAIServiceMockRecorder {
	return m.recorder
}

// AnalyzeCoin mocks base method.
func (m *MockAIService) AnalyzeCoin(ctx context.Context, frontImagePath, backImagePath, modelName string, temperature float32, lang string) (*domain.CoinAnalysisResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeCoin", ctx, frontImagePath, backImagePath, modelName, temperature, lang)
	ret0, _ := ret[0].(*domain.CoinAnalysisResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeCoin indicates an expected call of AnalyzeCoin.
func (mr *MockAIServiceMockRecorder) AnalyzeCoin(ctx, frontImagePath, backImagePath, modelName, temperature, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeCoin", reflect.TypeOf((*MockAIService)(nil).AnalyzeCoin), ctx, frontImagePath, backImagePath, modelName, temperature, lang)
}

// ListModels mocks base method.
func (m *MockAIService) ListModels(ctx context.Context) ([]domain.GeminiModelInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", ctx)
	ret0, _ := ret[0].([]domain.GeminiModelInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockAIServiceMockRecorder) ListModels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockAIService)(nil).ListModels), ctx)
}
