// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/antonioparicio/numismaticapp/internal/domain (interfaces: PriceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mocks/mock_price_client.go -package=mocks github.com/antonioparicio/numismaticapp/internal/domain PriceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPriceClient is a mock of PriceClient interface.
type MockPriceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPriceClientMockRecorder
}

// MockPriceClientMockRecorder is the mock recorder for MockPriceClient.
type MockPriceClientMockRecorder struct {
	mock *MockPriceClient
}

// NewMockPriceClient creates a new mock instance.
func NewMockPriceClient(ctrl *gomock.Controller) *MockPriceClient {
	mock := &MockPriceClient{ctrl: ctrl}
	mock.recorder = &MockPriceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceClient) EXPECT() *MockPriceClientMockRecorder {
	return m.recorder
}

// GetMetalPrices mocks base method.
func (m *MockPriceClient) GetMetalPrices(arg0 context.Context) (float64, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetalPrices", arg0)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMetalPrices indicates an expected call of GetMetalPrices.
func (mr *MockPriceClientMockRecorder) GetMetalPrices(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetalPrices", reflect.TypeOf((*MockPriceClient)(nil).GetMetalPrices), arg0)
}
