// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/antonioparicio/numismaticapp/internal/domain (interfaces: CoinRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mocks/mock_coin_repository.go -package=mocks github.com/antonioparicio/numismaticapp/internal/domain CoinRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	"time"

	domain "github.com/antonioparicio/numismaticapp/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCoinRepository is a mock of CoinRepository interface.
type MockCoinRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCoinRepositoryMockRecorder
	isgomock struct{}
}

// MockCoinRepositoryMockRecorder is the mock recorder for MockCoinRepository.
type MockCoinRepositoryMockRecorder struct {
	mock *MockCoinRepository
}

// NewMockCoinRepository creates a new mock instance.
func NewMockCoinRepository(ctrl *gomock.Controller) *MockCoinRepository {
	mock := &MockCoinRepository{ctrl: ctrl}
	mock.recorder = &MockCoinRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoinRepository) EXPECT() *MockCoinRepositoryMockRecorder {
	return m.recorder
}

// AddImage mocks base method.
func (m *MockCoinRepository) AddImage(ctx context.Context, image domain.CoinImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddImage", ctx, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddImage indicates an expected call of AddImage.
func (mr *MockCoinRepositoryMockRecorder) AddImage(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddImage", reflect.TypeOf((*MockCoinRepository)(nil).AddImage), ctx, image)
}

// Count mocks base method.
func (m *MockCoinRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockCoinRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockCoinRepository)(nil).Count), ctx)
}

// Delete mocks base method.
func (m *MockCoinRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCoinRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCoinRepository)(nil).Delete), ctx, id)
}

// GetAllCoins mocks base method.
func (m *MockCoinRepository) GetAllCoins(ctx context.Context) ([]*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCoins", ctx)
	ret0, _ := ret[0].([]*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCoins indicates an expected call of GetAllCoins.
func (mr *MockCoinRepositoryMockRecorder) GetAllCoins(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCoins", reflect.TypeOf((*MockCoinRepository)(nil).GetAllCoins), ctx)
}

// GetAllValues mocks base method.
func (m *MockCoinRepository) GetAllValues(ctx context.Context) ([]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllValues", ctx)
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllValues indicates an expected call of GetAllValues.
func (mr *MockCoinRepositoryMockRecorder) GetAllValues(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllValues", reflect.TypeOf((*MockCoinRepository)(nil).GetAllValues), ctx)
}

// GetAverageValue mocks base method.
func (m *MockCoinRepository) GetAverageValue(ctx context.Context) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageValue", ctx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageValue indicates an expected call of GetAverageValue.
func (mr *MockCoinRepositoryMockRecorder) GetAverageValue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageValue", reflect.TypeOf((*MockCoinRepository)(nil).GetAverageValue), ctx)
}

// GetByID mocks base method.
func (m *MockCoinRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCoinRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCoinRepository)(nil).GetByID), ctx, id)
}

// GetCountryDistribution mocks base method.
func (m *MockCoinRepository) GetCountryDistribution(ctx context.Context) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountryDistribution", ctx)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountryDistribution indicates an expected call of GetCountryDistribution.
func (mr *MockCoinRepositoryMockRecorder) GetCountryDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountryDistribution", reflect.TypeOf((*MockCoinRepository)(nil).GetCountryDistribution), ctx)
}

// GetGradeDistribution mocks base method.
func (m *MockCoinRepository) GetGradeDistribution(ctx context.Context) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGradeDistribution", ctx)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGradeDistribution indicates an expected call of GetGradeDistribution.
func (mr *MockCoinRepositoryMockRecorder) GetGradeDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGradeDistribution", reflect.TypeOf((*MockCoinRepository)(nil).GetGradeDistribution), ctx)
}

// GetGroupDistribution mocks base method.
func (m *MockCoinRepository) GetGroupDistribution(ctx context.Context) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupDistribution", ctx)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupDistribution indicates an expected call of GetGroupDistribution.
func (mr *MockCoinRepositoryMockRecorder) GetGroupDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupDistribution", reflect.TypeOf((*MockCoinRepository)(nil).GetGroupDistribution), ctx)
}

// GetGroupStats mocks base method.
func (m *MockCoinRepository) GetGroupStats(ctx context.Context) ([]domain.GroupStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupStats", ctx)
	ret0, _ := ret[0].([]domain.GroupStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupStats indicates an expected call of GetGroupStats.
func (mr *MockCoinRepositoryMockRecorder) GetGroupStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupStats", reflect.TypeOf((*MockCoinRepository)(nil).GetGroupStats), ctx)
}

// GetHeaviestCoin mocks base method.
func (m *MockCoinRepository) GetHeaviestCoin(ctx context.Context) (*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaviestCoin", ctx)
	ret0, _ := ret[0].(*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaviestCoin indicates an expected call of GetHeaviestCoin.
func (mr *MockCoinRepositoryMockRecorder) GetHeaviestCoin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaviestCoin", reflect.TypeOf((*MockCoinRepository)(nil).GetHeaviestCoin), ctx)
}

// GetMaterialDistribution mocks base method.
func (m *MockCoinRepository) GetMaterialDistribution(ctx context.Context) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterialDistribution", ctx)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaterialDistribution indicates an expected call of GetMaterialDistribution.
func (mr *MockCoinRepositoryMockRecorder) GetMaterialDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterialDistribution", reflect.TypeOf((*MockCoinRepository)(nil).GetMaterialDistribution), ctx)
}

// GetOldestCoin mocks base method.
func (m *MockCoinRepository) GetOldestCoin(ctx context.Context) (*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOldestCoin", ctx)
	ret0, _ := ret[0].(*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOldestCoin indicates an expected call of GetOldestCoin.
func (mr *MockCoinRepositoryMockRecorder) GetOldestCoin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOldestCoin", reflect.TypeOf((*MockCoinRepository)(nil).GetOldestCoin), ctx)
}

// GetRandomCoin mocks base method.
func (m *MockCoinRepository) GetRandomCoin(ctx context.Context) (*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomCoin", ctx)
	ret0, _ := ret[0].(*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomCoin indicates an expected call of GetRandomCoin.
func (mr *MockCoinRepositoryMockRecorder) GetRandomCoin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomCoin", reflect.TypeOf((*MockCoinRepository)(nil).GetRandomCoin), ctx)
}

// GetRarestCoins mocks base method.
func (m *MockCoinRepository) GetRarestCoins(ctx context.Context, limit int) ([]*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRarestCoins", ctx, limit)
	ret0, _ := ret[0].([]*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRarestCoins indicates an expected call of GetRarestCoins.
func (mr *MockCoinRepositoryMockRecorder) GetRarestCoins(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRarestCoins", reflect.TypeOf((*MockCoinRepository)(nil).GetRarestCoins), ctx, limit)
}

// GetSmallestCoin mocks base method.
func (m *MockCoinRepository) GetSmallestCoin(ctx context.Context) (*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSmallestCoin", ctx)
	ret0, _ := ret[0].(*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSmallestCoin indicates an expected call of GetSmallestCoin.
func (mr *MockCoinRepositoryMockRecorder) GetSmallestCoin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSmallestCoin", reflect.TypeOf((*MockCoinRepository)(nil).GetSmallestCoin), ctx)
}

// GetTotalValue mocks base method.
func (m *MockCoinRepository) GetTotalValue(ctx context.Context) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalValue", ctx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalValue indicates an expected call of GetTotalValue.
func (mr *MockCoinRepositoryMockRecorder) GetTotalValue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalValue", reflect.TypeOf((*MockCoinRepository)(nil).GetTotalValue), ctx)
}

// GetTotalWeightByMaterial mocks base method.
func (m *MockCoinRepository) GetTotalWeightByMaterial(ctx context.Context, materialLike string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalWeightByMaterial", ctx, materialLike)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalWeightByMaterial indicates an expected call of GetTotalWeightByMaterial.
func (mr *MockCoinRepositoryMockRecorder) GetTotalWeightByMaterial(ctx, materialLike any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalWeightByMaterial", reflect.TypeOf((*MockCoinRepository)(nil).GetTotalWeightByMaterial), ctx, materialLike)
}

// List mocks base method.
func (m *MockCoinRepository) List(ctx context.Context, filter domain.CoinFilter) ([]*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCoinRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCoinRepository)(nil).List), ctx, filter)
}

// ListRecent mocks base method.
func (m *MockCoinRepository) ListRecent(ctx context.Context) ([]*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecent", ctx)
	ret0, _ := ret[0].([]*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecent indicates an expected call of ListRecent.
func (mr *MockCoinRepositoryMockRecorder) ListRecent(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecent", reflect.TypeOf((*MockCoinRepository)(nil).ListRecent), ctx)
}

// ListTopValuable mocks base method.
func (m *MockCoinRepository) ListTopValuable(ctx context.Context) ([]*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopValuable", ctx)
	ret0, _ := ret[0].([]*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopValuable indicates an expected call of ListTopValuable.
func (mr *MockCoinRepositoryMockRecorder) ListTopValuable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopValuable", reflect.TypeOf((*MockCoinRepository)(nil).ListTopValuable), ctx)
}

// Save mocks base method.
func (m *MockCoinRepository) Save(ctx context.Context, coin *domain.Coin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, coin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCoinRepositoryMockRecorder) Save(ctx, coin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCoinRepository)(nil).Save), ctx, coin)
}

// Update mocks base method.
func (m *MockCoinRepository) Update(ctx context.Context, coin *domain.Coin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, coin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCoinRepositoryMockRecorder) Update(ctx, coin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCoinRepository)(nil).Update), ctx, coin)
}

// GetSaleChannels mocks base method.
func (m *MockCoinRepository) GetSaleChannels(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSaleChannels", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSaleChannels indicates an expected call of GetSaleChannels.
func (mr *MockCoinRepositoryMockRecorder) GetSaleChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSaleChannels", reflect.TypeOf((*MockCoinRepository)(nil).GetSaleChannels), ctx)
}

// MarkAsSold mocks base method.
func (m *MockCoinRepository) MarkAsSold(ctx context.Context, id uuid.UUID, soldAt time.Time, soldPrice float64, saleChannel string) (*domain.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsSold", ctx, id, soldAt, soldPrice, saleChannel)
	ret0, _ := ret[0].(*domain.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkAsSold indicates an expected call of MarkAsSold.
func (mr *MockCoinRepositoryMockRecorder) MarkAsSold(ctx, id, soldAt, soldPrice, saleChannel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsSold", reflect.TypeOf((*MockCoinRepository)(nil).MarkAsSold), ctx, id, soldAt, soldPrice, saleChannel)
}

// AddLink mocks base method.
func (m *MockCoinRepository) AddLink(ctx context.Context, link *domain.CoinLink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLink indicates an expected call of AddLink.
func (mr *MockCoinRepositoryMockRecorder) AddLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockCoinRepository)(nil).AddLink), ctx, link)
}

// RemoveLink mocks base method.
func (m *MockCoinRepository) RemoveLink(ctx context.Context, linkID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLink", ctx, linkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLink indicates an expected call of RemoveLink.
func (mr *MockCoinRepositoryMockRecorder) RemoveLink(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLink", reflect.TypeOf((*MockCoinRepository)(nil).RemoveLink), ctx, linkID)
}

// ListLinks mocks base method.
func (m *MockCoinRepository) ListLinks(ctx context.Context, coinID uuid.UUID) ([]*domain.CoinLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLinks", ctx, coinID)
	ret0, _ := ret[0].([]*domain.CoinLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLinks indicates an expected call of ListLinks.
func (mr *MockCoinRepositoryMockRecorder) ListLinks(ctx, coinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLinks", reflect.TypeOf((*MockCoinRepository)(nil).ListLinks), ctx, coinID)
}

// GetLink mocks base method.
func (m *MockCoinRepository) GetLink(ctx context.Context, linkID uuid.UUID) (*domain.CoinLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", ctx, linkID)
	ret0, _ := ret[0].(*domain.CoinLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockCoinRepositoryMockRecorder) GetLink(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockCoinRepository)(nil).GetLink), ctx, linkID)
}

// UpdateLink mocks base method.
func (m *MockCoinRepository) UpdateLink(ctx context.Context, link *domain.CoinLink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLink", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLink indicates an expected call of UpdateLink.
func (mr *MockCoinRepositoryMockRecorder) UpdateLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLink", reflect.TypeOf((*MockCoinRepository)(nil).UpdateLink), ctx, link)
}

// GetAllImages mocks base method.
func (m *MockCoinRepository) GetAllImages(ctx context.Context) ([]domain.CoinImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllImages", ctx)
	ret0, _ := ret[0].([]domain.CoinImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllImages indicates an expected call of GetAllImages.
func (mr *MockCoinRepositoryMockRecorder) GetAllImages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllImages", reflect.TypeOf((*MockCoinRepository)(nil).GetAllImages), ctx)
}

// GetAllLinks mocks base method.
func (m *MockCoinRepository) GetAllLinks(ctx context.Context) ([]*domain.CoinLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinks", ctx)
	ret0, _ := ret[0].([]*domain.CoinLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLinks indicates an expected call of GetAllLinks.
func (mr *MockCoinRepositoryMockRecorder) GetAllLinks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinks", reflect.TypeOf((*MockCoinRepository)(nil).GetAllLinks), ctx)
}
