// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/antonioparicio/numismaticapp/internal/domain (interfaces: BackgroundRemover)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mocks/mock_background_remover.go -package=mocks github.com/antonioparicio/numismaticapp/internal/domain BackgroundRemover
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBackgroundRemover is a mock of BackgroundRemover interface.
type MockBackgroundRemover struct {
	ctrl     *gomock.Controller
	recorder *MockBackgroundRemoverMockRecorder
	isgomock struct{}
}

// MockBackgroundRemoverMockRecorder is the mock recorder for MockBackgroundRemover.
type MockBackgroundRemoverMockRecorder struct {
	mock *MockBackgroundRemover
}

// NewMockBackgroundRemover creates a new mock instance.
func NewMockBackgroundRemover(ctrl *gomock.Controller) *MockBackgroundRemover {
	mock := &MockBackgroundRemover{ctrl: ctrl}
	mock.recorder = &MockBackgroundRemoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackgroundRemover) EXPECT() *MockBackgroundRemoverMockRecorder {
	return m.recorder
}

// RemoveBackground mocks base method.
func (m *MockBackgroundRemover) RemoveBackground(ctx context.Context, image []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBackground", ctx, image)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveBackground indicates an expected call of RemoveBackground.
func (mr *MockBackgroundRemoverMockRecorder) RemoveBackground(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBackground", reflect.TypeOf((*MockBackgroundRemover)(nil).RemoveBackground), ctx, image)
}
