// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/antonioparicio/numismaticapp/internal/domain (interfaces: ImageService)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mocks/mock_image_service.go -package=mocks github.com/antonioparicio/numismaticapp/internal/domain ImageService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImageService is a mock of ImageService interface.
type MockImageService struct {
	ctrl     *gomock.Controller
	recorder *MockImageServiceMockRecorder
	isgomock struct{}
}

// MockImageServiceMockRecorder is the mock recorder for MockImageService.
type MockImageServiceMockRecorder struct {
	mock *MockImageService
}

// NewMockImageService creates a new mock instance.
func NewMockImageService(ctrl *gomock.Controller) *MockImageService {
	mock := &MockImageService{ctrl: ctrl}
	mock.recorder = &MockImageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageService) EXPECT() *MockImageServiceMockRecorder {
	return m.recorder
}

// CropToCircle mocks base method.
func (m *MockImageService) CropToCircle(imagePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CropToCircle", imagePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CropToCircle indicates an expected call of CropToCircle.
func (mr *MockImageServiceMockRecorder) CropToCircle(imagePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CropToCircle", reflect.TypeOf((*MockImageService)(nil).CropToCircle), imagePath)
}

// CropToContent mocks base method.
func (m *MockImageService) CropToContent(image []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CropToContent", image)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CropToContent indicates an expected call of CropToContent.
func (mr *MockImageServiceMockRecorder) CropToContent(image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CropToContent", reflect.TypeOf((*MockImageService)(nil).CropToContent), image)
}

// GenerateThumbnail mocks base method.
func (m *MockImageService) GenerateThumbnail(imagePath string, width int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateThumbnail", imagePath, width)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateThumbnail indicates an expected call of GenerateThumbnail.
func (mr *MockImageServiceMockRecorder) GenerateThumbnail(imagePath, width any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateThumbnail", reflect.TypeOf((*MockImageService)(nil).GenerateThumbnail), imagePath, width)
}

// GetMetadata mocks base method.
func (m *MockImageService) GetMetadata(imagePath string) (int, int, int64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", imagePath)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(string)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockImageServiceMockRecorder) GetMetadata(imagePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockImageService)(nil).GetMetadata), imagePath)
}

// ProcessCoinImages mocks base method.
func (m *MockImageService) ProcessCoinImages(frontPath, backPath string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessCoinImages", frontPath, backPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ProcessCoinImages indicates an expected call of ProcessCoinImages.
func (mr *MockImageServiceMockRecorder) ProcessCoinImages(frontPath, backPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessCoinImages", reflect.TypeOf((*MockImageService)(nil).ProcessCoinImages), frontPath, backPath)
}

// Rotate mocks base method.
func (m *MockImageService) Rotate(imagePath string, angle float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", imagePath, angle)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rotate indicates an expected call of Rotate.
func (mr *MockImageServiceMockRecorder) Rotate(imagePath, angle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockImageService)(nil).Rotate), imagePath, angle)
}
