// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/coin_service.go
//
// Generated by this command:
//
//	mockgen -destination=internal/application/mocks/mock_application.go -package=mocks -source=internal/application/coin_service.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	numista "github.com/antonioparicio/numismaticapp/internal/infrastructure/numista"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNumistaService is a mock of NumistaService interface.
type MockNumistaService struct {
	ctrl     *gomock.Controller
	recorder *MockNumistaServiceMockRecorder
	isgomock struct{}
}

// MockNumistaServiceMockRecorder is the mock recorder for MockNumistaService.
type MockNumistaServiceMockRecorder struct {
	mock *MockNumistaService
}

// NewMockNumistaService creates a new mock instance.
func NewMockNumistaService(ctrl *gomock.Controller) *MockNumistaService {
	mock := &MockNumistaService{ctrl: ctrl}
	mock.recorder = &MockNumistaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNumistaService) EXPECT() *MockNumistaServiceMockRecorder {
	return m.recorder
}

// GetType mocks base method.
func (m *MockNumistaService) GetType(ctx context.Context, id int) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType", ctx, id)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetType indicates an expected call of GetType.
func (mr *MockNumistaServiceMockRecorder) GetType(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockNumistaService)(nil).GetType), ctx, id)
}

// SearchTypes mocks base method.
func (m *MockNumistaService) SearchTypes(ctx context.Context, query, category, year, issuer string, count int) (*numista.TypeSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTypes", ctx, query, category, year, issuer, count)
	ret0, _ := ret[0].(*numista.TypeSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTypes indicates an expected call of SearchTypes.
func (mr *MockNumistaServiceMockRecorder) SearchTypes(ctx, query, category, year, issuer, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTypes", reflect.TypeOf((*MockNumistaService)(nil).SearchTypes), ctx, query, category, year, issuer, count)
}

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
	isgomock struct{}
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// EnsureDir mocks base method.
func (m *MockStorageService) EnsureDir(coinID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDir", coinID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureDir indicates an expected call of EnsureDir.
func (mr *MockStorageServiceMockRecorder) EnsureDir(coinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDir", reflect.TypeOf((*MockStorageService)(nil).EnsureDir), coinID)
}

// SaveFile mocks base method.
func (m *MockStorageService) SaveFile(coinID uuid.UUID, filename string, content io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", coinID, filename, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveFile indicates an expected call of SaveFile.
func (mr *MockStorageServiceMockRecorder) SaveFile(coinID, filename, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockStorageService)(nil).SaveFile), coinID, filename, content)
}
